<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite42508292516be577cea7179a047e79a
{
    public static $prefixLengthsPsr4 = array (
        'N' => 
        array (
            'Nvm\\Donor\\' => 10,
        ),
        'D' => 
        array (
            'Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => 55,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Nvm\\Donor\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
        'Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => 
        array (
            0 => __DIR__ . '/..' . '/dealerdirect/phpcodesniffer-composer-installer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite42508292516be577cea7179a047e79a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite42508292516be577cea7179a047e79a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite42508292516be577cea7179a047e79a::$classMap;

        }, null, ClassLoader::class);
    }
}
